logging:
    config: classpath:logback.xml
server:
    port: 8119
    tomcat:
        uri-encoding: UTF-8
    undertow:
        accesslog:
            dir: ./logs
            enabled: false
            pattern: common
            prefix: access_log
            rotate: true
            suffix: log
management:
    security:
        enabled: false
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        initialSize: 5
        logSlowSql: true
        maxActive: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        dbhost: 119.23.253.160
        dbname: project_demo
        username: dbadmin
        password: eq1000..@
        url: jdbc:mysql://${spring.datasource.dbhost}/${spring.datasource.dbname}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        validationQuery: SELECT 1 FROM DUAL
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        multipart:
            max-file-size: 60MB
            max-request-size: 60MB
